services:
    postgres:
        container_name: postgres-dev
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data-dev:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G

    minio:
        container_name: minio-dev
        image: minio/minio:latest
        command: server --console-address ":9001" /data
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio-storage:/data
            - minio-config:/root/.minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

volumes:
    postgres-data-dev:
    minio-storage:
    minio-config:
