services:
    postgres:
        container_name: postgres-test
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data-test:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 1G

volumes:
    postgres-data-test:
